### ISSUE TITLE
`--user` switch not working

### ISSUE THREAD

**Issue by cedx** [cedx/reverse-proxy.js#5]
When I use the `--user` switch, I get the following error:

```
$ bin/cli.js --target=9000 --user=www-data
Reverse proxy instance listening on 0.0.0.0:3000
TypeError: this.log is not a function
    at Application.setUser (/repo/reverse-proxy.js/lib/application.js:103:12)
    at /repo/reverse-proxy.js/lib/application.js:91:46
    at Generator.next (<anonymous>)
    at step (/repo/reverse-proxy.js/lib/application.js:28:191)
    at /repo/reverse-proxy.js/lib/application.js:28:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by cedx** [comment]
Fixed in version 4.0.1.
